# Catppuccin Latte for Moodle Storage
theme[main_bg]="#eff1f5"
theme[main_fg]="#4c4f69"
theme[title]="#4c4f69"
theme[hi_fg]="#1e66f5"
theme[selected_bg]="#ccd0da"
theme[selected_fg]="#1e66f5"
theme[inactive_fg]="#7c7f93"
theme[cpu_box]="#8839ef"
theme[mem_box]="#40a02b"
theme[div_line]="#9ca0b0"
theme[used_start]="#40a02b"
theme[available_mid]="#df8e1d"
theme[available_end]="#d20f39"
