# Catppuccin Frappe for Moodle Storage
theme[main_bg]="#303446"
theme[main_fg]="#c6d0f5"
theme[title]="#c6d0f5"
theme[hi_fg]="#8caaee"
theme[selected_bg]="#414559"
theme[selected_fg]="#8caaee"
theme[inactive_fg]="#838ba7"
theme[cpu_box]="#ca9ee6"
theme[mem_box]="#a6d189"
theme[div_line]="#737994"
theme[used_start]="#a6d189"
theme[available_mid]="#e5c890"
theme[available_end]="#e78284"
