# Catppuccin Macchiato for Moodle Storage
theme[main_bg]="#24273a"
theme[main_fg]="#cad3f5"
theme[title]="#cad3f5"
theme[hi_fg]="#8aadf4"
theme[selected_bg]="#363a4f"
theme[selected_fg]="#8aadf4"
theme[inactive_fg]="#8087a2"
theme[cpu_box]="#c6a0f6"
theme[mem_box]="#a6da95"
theme[div_line]="#6e738d"
theme[used_start]="#a6da95"
theme[available_mid]="#eed49f"
theme[available_end]="#ed8796"
