# Gruvbox Light for Moodle Storage
theme[main_bg]="#fbf1c7"
theme[main_fg]="#3c3836"
theme[title]="#3c3836"
theme[hi_fg]="#076678"
theme[selected_bg]="#ebdbb2"
theme[selected_fg]="#b57614"
theme[inactive_fg]="#7c6f64"
theme[cpu_box]="#8f3f71"
theme[mem_box]="#79740e"
theme[div_line]="#d5c4a1"
theme[used_start]="#79740e"
theme[available_mid]="#b57614"
theme[available_end]="#9d0006"
