# Solarized Dark for Moodle Storage
theme[main_bg]="#002b36"
theme[main_fg]="#839496"
theme[title]="#93a1a1"
theme[hi_fg]="#268bd2"
theme[selected_bg]="#073642"
theme[selected_fg]="#b58900"
theme[inactive_fg]="#586e75"
theme[cpu_box]="#d33682"
theme[mem_box]="#859900"
theme[div_line]="#073642"
theme[used_start]="#859900"
theme[available_mid]="#b58900"
theme[available_end]="#dc322f"
